### PR TITLE
Index.html: add responsive design

### PR DESCRIPTION
**Pull request by nyatindopatrick**
The responsiveness has been successfully tested on desktop, tablet and mobile views.

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @nyatindopatrick  :wave: 

### This is a great effort :muscle: your use of bootstrap is the ideal :ok_hand:  :medal_sports: please address to the changes require bellow :point_down: 

## Small Screens

**Navbar**
 
- [ ] The "Sign In" font has to be bigger and you are missing the hamburger button in the rightmost part of the navbar, like the original

- Yours

image

- Original

image

**Section Positioning**

- [ ] Please follow the structure for the first 4 sections in this screen size:

1. TOP STORY
2. MORE STORIES
3. CULTURE & TRAVEL
4. FEATURED STORIES

- Yours

image

- Original
 
image

**MORE STORIES, LATEST NEWS, and the aside articles of the U.S, World, Business, Tech & Science, Culture and Sports**

- [ ] The image of the articles of these sections should take 60% of the screen width and the headline only 40%

- Yours

image

- Original

image

**IN THE MAGAZINE**

- [ ] The IN THE MAGAZINE title has to come after the preview magazine

- Yours

image

- Original

image

## Small and Medium screens

**IN THE MAGAZINE, EDITOR'S PICK and FEATURED SLIDE SHOW**

- [ ] The title has to take 100% of the screen width, yours seem to be splitting in two lines

- Yours

image

- Original

image

## Medium Screens

**SUBSCRIBE and NEWSLETTER**

- [ ] The content should be closer to the images, also the titles are cut in several sections

- Yours

image

- Original

image

## Big Screens

**Navbar**

- [ ] The NEWSWEEK logo should be bigger and more centered in the middle of the navbar, separate the SIGN IN button in the navbar from the right side, center the navigation links a little or spread them more to make it more similar to the original, the navigation links background should be white

- Yours

image

- Original

image

## Generals

- [ ] The headings for all articles should be bold or bolder and the font should be noticeable bigger from the content font

- Yours

image

- Original

image

**NEWSLETTER**

- [ ] You are missing the title for this section 

- Yours

image

- Original

image

## That's it! :raised_hands: 

## Please :pray: do the changes :memo: and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

Any questions? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work building this @nyatindopatrick! :handshake: 
Please consider my comments below, make the appropriate changes and request another review.

#### Responsiveness
The issues I encountered reviewing your project all revolve around the responsiveness of the page and as such I have attached some screenshots below:

* Missing navigation
Please consider the following screenshot, the navigation bar is missing on the table screens sizes which range from 768px down to 425px. View it [here](https://images2.imgbox.com/12/7b/7srDq20j_o.gif)

#### Subscribe and Newsletter Section
Please consider taking a second look at the responsiveness for the newsletter section towards the bottom of the page, and make the appropriate changes
screenshot

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).
images

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for feedback

**Comment by nikasulo** [comment]
# Nice work attempting to make the proposed changes @nyatindopatrick 
Your effort is really showing :ok_hand, however, it seems like the changes you made broke a few more things. Please consider the following screenshots of the sections in question, try to inspect them closely, make the necessary changes and request another review :+1: 

screenshot
screenshot
screenshot
screenshot
screenshot

### Summary
It is imperative that you get the responsiveness right as it is a hard requirement for this project. Please compare your project thoroughly with the original site on all screen sizes and in all aspects

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by rOluochKe — APPROVED** [review]
Hello Team,

### Congratulations :clap: :boom: Your project has been approved.
### You can merge and submit a project completion form from your dashboard.

**Pull request merged**
